# Superstore Sales Analysis
## Margin Erosion & Regional Performance

**Goal:** Identify which product categories and regions are 
underperforming on profit margin, and provide actionable 
recommendations for the business.

**Dataset:** Superstore Sales 2014-2017 | 9,994 orders | 21 columns  
**Source:** Kaggle — Vivek Chowdhury  
**Stack:** Python (pandas, matplotlib, seaborn) | PostgreSQL | Power BI

---

## 0. Global setup and imports

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sqlalchemy import create_engine

engine = create_engine('postgresql://postgres:postgres@localhost:5432/superstore')
print('Motore SQL pronto.')

Motore SQL pronto.

## 1. Loading Raw Data
Loading the original dataset as-is, without any modifications.
Preserving the source data for reference and reproducibility.

In [3]:
raw_superstore = pd.read_csv('./data/raw/superstore.csv', encoding='latin-1')

raw_superstore.to_sql('orders_raw', engine, if_exists='replace', index=False)
print(f"Dati grezzi caricati correttamente. Righe totali: {len(raw_superstore)}")

Dati grezzi caricati correttamente. Righe totali: 9994

## 2. Initial Exploration
Understanding the dataset structure, data types, missing values,
and basic statistics before any transformation.

In [ ]:
# types and null values check
raw_superstore.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   str
 3   Ship Date      9994 non-null   str
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), str(15)
memory usage: 1.6 MB

In [ ]:
# numerical vars statistical analysis
raw_superstore.describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55190.379428,229.858001,3.789574,0.156203,28.656896
std,2885.163629,32063.693350,623.245101,2.225110,0.206452,234.260108
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000

In [ ]:
# visual sanity check on first rows of the raw dataset
raw_superstore.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

### Section 2 Summary — Key Observations

* **Dataset Dimensions:** The dataset presents 9,994 rows and 21 columns. However, column names must be normalized to the `snake_case` naming convention for better programmatic handling.
* **Missing Values:** No critical null values were found across the main analytical fields.
* **Profit Drain Confirmation:** The extreme negative minimum value found in the `Profit` column via `.describe()` experimentally confirms our initial hypothesis regarding heavy losses on specific sub-categories (like Tables or Bookcases) observed during the Excel exploration.
* **Data Type Issues:** The `info()` and `head()` methods reveal that date fields (`Order Date` and `Ship Date`) are currently stored as strings (object) and do not follow the international `YYYY-MM-DD` standard format. This will be resolved in the cleaning phase to allow time-series analysis.

## 3. Data Cleaning
Standardizing column names to snake_case, fixing date types,
handling missing values, and creating derived columns.
All cleaning decisions are documented inline.

## 4. Loading Raw Data to PostgreSQL
Loading the original uncleaned dataset to PostgreSQL as `orders_raw`.
This preserves a reference copy of the source data in the database.

## 5. Loading Clean Data to PostgreSQL
Loading the cleaned and transformed dataset to PostgreSQL as `orders_clean`.
All subsequent SQL queries will run on this table.

## 6. SQL Exploration
Answering the business questions through SQL queries on `orders_clean`.
Each query includes a comment explaining its business rationale.

## 7. Analysis & Visualizations

### 7.1 Margin Analysis by Category

### 7.2 Discount vs Profit Relationship

### 7.3 Regional Performance

### 7.4 Seasonal Trends


### 7.5 Key Findings Summary